---
name: release

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: version
        run: echo "version=$(./nfhelp.sh -v)" >> $GITHUB_ENV
        id: version
        
      - name: Tar files
        run: tar -zcvf nfhelp.tar.gz nfhelp.sh

      - name: release
        uses: ncipollo/release-action@v1
        id: release
        with:
          draft: false
          prerelease: false
          tag: v${{ env.version }}
          artifacts: nfhelp.tar.gz
          artifactContentType: application/gzip
        env:
          GITHUB_TOKEN: ${{ github.token }}
